site_name: France périphérique & systèmes complexes
theme:
  name: null
  custom_dir: 'cinder'
nav:
  - Accueil : index.md
  - Méthodes : methodes.md
  - Cartographie : cartographie.md
  - Polarisation : polarisation.md
  - Analyse causale : analyse.md
  - Conclusion : conclusion.md
